@startuml ESL_ユースケース図
left to right direction
actor "クライアントアプリ\n(ユーザ)" as cltapp
together {
    actor "AWS Lambda" as aws_lambda
    actor "AWS S3" as aws_s3
}
together {
    actor "Epaper SDKサーバ" as sdksrv
    actor "Epaper端末" as epaper
}

package "Epaper画像書き込み" {
    usecase 撮影した写真を登録 as register_camera
    usecase アルバムで選択した画像を登録 as register_album_picture
    usecase トリミング画像を登録 as register_trim_image
    usecase 配信用画像をサーバに登録 as register_image
    usecase 配信用画像を一覧表示 as view_images
    usecase 登録画像の削除 as delete_images
    usecase 画像配信 as stream_image
    usecase BT接続 as connect_bt
    register_camera --|> register_image
    register_album_picture --|> register_image
    register_trim_image --|> register_image
}
cltapp -- register_camera
cltapp -- register_album_picture
cltapp -- register_trim_image
cltapp -- view_images
cltapp -- delete_images
cltapp -- stream_image
cltapp -- connect_bt

register_image -- aws_lambda
view_images -- aws_lambda
stream_image -- aws_lambda
delete_images -- aws_lambda

view_images -- aws_s3
register_image -- aws_s3
stream_image -- aws_s3
delete_images -- aws_s3

stream_image --- sdksrv

stream_image -- epaper
connect_bt -- epaper
@enduml
