@startuml ESLアプリサーバシーケンス図
skinparam Monochrome true
hide footbox

actor "ユーザ" as user
participant "クライアントアプリ" as cltapp
participant "AWS Lambda" as aws_lambda
database "画像ID⇔画像URLの紐づけ\n(AWS DynamoDB)" as hash_table
participant "AWS S3" as aws_s3
database "画像ファイル\n(AWS S3保存)" as imageDatas
participant "Epaper SDKサーバ" as sdksrv
participant "Epaper端末" as epaper

note over aws_lambda, imageDatas
    ※DynamoDB, S3へのアクセス設定はlambda側に設定済みとする
end note

== 配信用画像をサーバに登録 ==
user ->> cltapp ++ : カメラ撮影 or\nアルバムから選択 or\nトリミング画像を選択
cltapp -> aws_lambda ++ : 署名付きURL取得\n(アップロード対象画像ファイルパスリスト)

loop アップロード対象画像ファイルパスリストの要素数
    aws_lambda -> aws_s3 ++ : 署名付きURL取得\n(画像ファイルパス)
    aws_lambda <-- aws_s3 -- : 署名付きURL取得 応答\n(アップロード用署名付きURL)
end
cltapp <-- aws_lambda -- : 署名付きURL取得 応答\n(ステータスコード, 画像ファイルパスに対応するアップロード用署名付きURLリスト)

opt 署名付きURL取得 応答が正常
    loop 追加登録画像数
        cltapp -> imageDatas : ファイルアップロード\n(画像ファイル)
    end
end
user <<-- cltapp --
note over user
    * 画像登録
    * 画像一覧表示
    * 画像配信
    のいずれかに遷移
end note

aws_s3 ->> aws_lambda ++ : ファイルアップロードイベント(アップロードされたファイルパス)
aws_lambda -> hash_table : DB更新
deactivate aws_lambda


== 配信用画像を一覧表示 ==
user ->> cltapp ++ : サムネ画像表示画面遷移
cltapp -> aws_lambda ++ : 画像リスト要求\n()
aws_lambda -> hash_table : テーブル内アイテム全件取得
aws_lambda <-- hash_table
loop DBのテーブル内アイテム数
    aws_lambda -> aws_s3 ++ : 署名付きURL取得\n(IDに対応する画像URL)
    aws_lambda <-- aws_s3 -- : 署名付きURL取得 応答\n(ダウンロード用署名付きURL)
end
cltapp <-- aws_lambda -- : 画像リスト要求 応答\n(ステータスコード, 画像IDに対応するダウンロード用署名付きURLリスト)
loop 画像IDに対応する画像URLリスト要素数
    cltapp -> imageDatas ++ : 画像取得\n()
    cltapp <-- imageDatas -- : 画像取得 応答\n(画像ファイル)
end
cltapp -> cltapp : 画像サムネ表示
user <<-- cltapp --


== 画像配信 ==
note over cltapp, epaper
    ※iPhone ⇔ Epaper端末はBT接続済みとする
end note
user ->> cltapp ++ : 画像配信
cltapp -> sdksrv ++ : 画像配信要求\n(画像ID)
sdksrv -> aws_lambda ++ : 画像要求\n(画像ID)
aws_lambda -> aws_s3 ++ : 署名付きURL取得\n(IDに対応する画像URL)
aws_lambda <-- aws_s3 -- : 署名付きURL取得 応答\n(ダウンロード用署名付きURL)
sdksrv <-- aws_lambda -- : 画像要求 応答\n(ダウンロード用署名付きURL)
sdksrv -> sdksrv : 配信画像準備
cltapp <-- sdksrv -- : 画像配信要求 応答\n(Epaper画像フォーマット)
par
    opt "画像変換成功"
        cltapp -> epaper ++ : 画像配信\n(Epaper画像フォーマット)
        epaper -> epaper -- : 画像表示
    end
else
    cltapp ->> aws_lambda ++ : 画像情報更新\n(ID, 画像変換結果)
    user <<-- cltapp --
    aws_lambda -> hash_table : DB更新
    deactivate aws_lambda
end

@enduml
