AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 5.65Epaper-app-server-api

Parameters:
  AwsS3Bucket:
    Type: String
    Default: 5.65-epaper-app-serever-assets
    Description: 画像アップロード/ダウンロード先S3バケット名

Resources:
  # ルーティング処理関数
  ApiLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: app.lambda_handler
      Runtime: python3.12
      Policies:
        # S3アクセス許可
        - S3CrudPolicy:
            BucketName: !Sub ${AwsS3Bucket}
      Environment:
        Variables:
          AWS_S3_BUCKET: !Sub ${AwsS3Bucket}
          LOG_LEVEL: 10
      Events:
        ApiRoot:
          Type: Api
          Properties:
            Path: '/'
            Method: ANY
        ApiProxy:
          Type: Api
          Properties:
            Path: '/{proxy+}'
            Method: ANY

  # ロググループ
  FunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${ApiLambdaFunction}
      RetentionInDays: 30

Outputs:
  FunctionUrl:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
